# Generated by Django 3.2.2 on 2021-05-10 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaxAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'Cantidad máxima',
                'verbose_name_plural': 'Cantidades máximas',
            },
        ),
        migrations.CreateModel(
            name='Motorcyler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_amount', models.IntegerField(verbose_name='Cantidad actual')),
                ('max_amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motorcyclers.maxamount', verbose_name='Cantidad máxima')),
            ],
            options={
                'verbose_name': 'Motociclista',
                'verbose_name_plural': 'Motociclistas',
                'ordering': ['id'],
            },
        ),
    ]
