# Generated by Django 3.2.3 on 2021-05-28 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorcyclers', '0002_motorcyler_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Motorcyler',
            new_name='Motorcycler',
        ),
    ]
